name: Build ArmorPaint Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Generate Project Files
      run: |
        node armorcore/make -g direct3d12
        cd armorcore
        node make -g direct3d12

    - name: Compile ArmorPaint
      run: msbuild armorcore/build/ArmorPaint.sln /p:Configuration=Release /p:Platform=x64

    - name: Prepare Output
      run: copy armorcore\build\x64\Release\ArmorPaint.exe build\krom\

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ArmorPaint-Windows
        path: build/krom/
